# Generated by Django 4.1.6 on 2023-04-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_first_name_user_last_name_user_male'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('student', 'student'), ('teacher', 'teacher')], default='student', max_length=20),
        ),
    ]
