# Generated by Django 4.1.6 on 2023-04-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('student', 'student'), ('teacher', 'teacher')], max_length=20),
        ),
    ]
