# Generated by Django 4.2 on 2023-04-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='male',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=20),
        ),
    ]
