version: "3.8"

services:
  db:
    image: postgres
    volumes:
      - ./data
    environment:
      - POSTGRES_DB=postgres2
      - POSTGRES_USER=postgres2
      - POSTGRES_PASSWORD=postgres2
  web: 
    build: .
    command: python3 manage.py runserver 0.0.0.0:8009
    ports:
      - "8009:8009"
    depends_on:
      - db 
