# Generated by Django 4.1.7 on 2023-04-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplephoto',
            name='photo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='topicphoto',
            name='photo',
            field=models.TextField(),
        ),
    ]
