# Generated by Django 4.1.6 on 2023-04-14 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='quiz',
        ),
    ]
